from pywebio import *
from pywebio.session import info as session_info
from dateutil.easter import *
import arrow
from pyecharts.components import Table

# UNDER HEAVY DEVELOPMENT - NOT FOR PRODUCTION USE

# §§
# LICENSE: https://github.com/quadratecode/piccolaw-apps/blob/master/LICENSE.md
# §§

# Custom config
config(title="Web App Fristenrechner | Web App Deadline Calculator",
      description="Berechne Fristen nach Schweizer Recht | Calculate Deadlines according to Swiss Law",
      css_file = "https://www.piccolaw.ch/pl_apps.css", # adjust for personal CSS
      theme = "default") 


# --- FUNCTIONS --- #

# Function to choose language according to browser language
def lang(eng, german):
    if 'de' in session_info.user_language:
        return german
    else:
        return eng

# Control bar functions
def btn_click(btn_val):
    if btn_val == "< Back to piccolaw.ch":
        session.run_js('window.location = "https://www.piccolaw.ch/"')
    elif btn_val == "Restart App":
        session.run_js('window.location.reload()')
    elif btn_val == "Feedback":
        session.run_js('open("mailto:hello@piccolaw.ch")')

# User Info: Employment data (block required)
def deadline_app():

    # --- SESSION CONTROL --- #
    session.set_env(input_panel_fixed=False,
                    output_animation=False)

    label_change = {
        lang("Actual receipt", "Tatsächlicher Empfang") : lang("Date of receipt", "Zustelldatum"),
        lang("Legal fiction", "Zustellfiktion") : lang("Date of collection note", "Datum Abholungseinladung"),
    }

    labels = list(label_change.keys())

    canton_change = {
        "AG" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False}, 
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : True, "selected": True},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : True, "selected": True},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : True, "selected": True},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : True, "selected": True},
            {"label" : "Mariä Empfängnis", "value" : True, "selected": True},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
        "AI" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : False, "selected": False},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : True, "selected": True},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : True, "selected": True},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : True, "selected": True},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : True, "selected": True},
            {"label" : "Mariä Empfängnis", "value" : True, "selected": True},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "AR" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : False, "selected": False},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : False, "selected": False},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : False, "selected": False},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : False, "selected": False},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "BS" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : False, "selected": False},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : True, "selected": True},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : False, "selected": False},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : False, "selected": False},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : False, "selected": False},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "BL" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : False, "selected": False},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : True, "selected": True},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : False, "selected": False},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : False, "selected": False},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : False, "selected": False},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "BE" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : False, "selected": False},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : False, "selected": False},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : False, "selected": False},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "FR" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : True, "selected": True},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : True, "selected": True},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : True, "selected": True},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "GE" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : False, "selected": False},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : False, "selected": False},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : False, "selected": False},
            {"label" : "Jeûne Genevois", "value" : True, "selected": True},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : False, "selected": False},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "False" : False, "selected": False},
            {"label" : "Restauration de la République", "value" : True, "selected": True},
        ],
    "GL" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : True, "selected": True},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : False, "selected": False},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : False, "selected": False},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : True, "selected": True},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "GR" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : False, "selected": False},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : False, "selected": False},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : False, "selected": False},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : False, "selected": False},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "JU" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : True, "selected": True},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : True, "selected": True},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : True, "selected": True},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : True, "selected": True},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : True, "selected": True},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : False, "selected": False},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "LU" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : True, "selected": True},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : True, "selected": True},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : True, "selected": True},
            {"label" : "Mariä Empfängnis", "value" : True, "selected": True},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "NE" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : True, "selected": True},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : False, "selected": False},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : True, "selected": True},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : True, "selected": True},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : False, "selected": False},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : False, "selected": False},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "NW" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : True, "selected": True},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : False, "selected": False},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : True, "selected": True},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : False, "selected": False},
            {"label" : "Mariä Empfängnis", "value" : True, "selected": True},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "OW" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : True, "selected": True},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : True, "selected": True},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : True, "selected": True},
            {"label" : "Allerheiligen", "value" : True, "selected": True},
            {"label" : "Mariä Empfängnis", "value" : True, "selected": True},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "SH" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : True, "selected": True},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : False, "selected": False},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : False, "selected": False},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : False, "selected": False},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "SZ" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : False, "selected": False},
            {"label" : "Heilige Drei Könige", "value" : True, "selected": True},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : True, "selected": True},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : True, "selected": True},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : True, "selected": True},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : True, "selected": True},
            {"label" : "Mariä Empfängnis", "value" : True, "selected": True},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "SO" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : True, "selected": True},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : True, "selected": True},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : True, "selected": True},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : True, "selected": True},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "SG" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : False, "selected": False},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : False, "selected": False},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : True, "selected": True},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "TG" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : True, "selected": True},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : False, "selected": False},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : False, "selected": False},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : False, "selected": False},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "TI" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : False, "selected": False},
            {"label" : "Heilige Drei Könige", "value" : True, "selected": True},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : True, "selected": True},
            {"label" : "Karfreitag", "value" : False, "selected": False},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : True, "selected": True},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : True, "selected": True},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : True, "selected": True},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : True, "selected": True},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : True, "selected": True},
            {"label" : "Mariä Empfängnis", "value" : True, "selected": True},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "UR" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : True, "selected": True},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : False, "selected": False},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : False, "selected": False},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : False, "selected": False},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "VS" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : True, "selected": True},
            {"label" : "Karfreitag", "value" : False, "selected": False},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : True, "selected": True},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : True, "selected": True},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : True, "selected": True},
            {"label" : "Mariä Empfängnis", "value" : True, "selected": True},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "VD" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : True, "selected": True},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : True, "selected": True},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : True, "selected": True},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : False, "selected": False},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : False, "selected": False},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "ZG" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : True, "selected": True},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : True, "selected": True},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : True, "selected": True},
            {"label" : "Mariä Empfängnis", "value" : True, "selected": True},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    "ZH" : [
            {"label" : "Neujahrstag", "value" : True, "selected": True},
            {"label" : "Berchtoldstag", "value" : True, "selected": True},
            {"label" : "Heilige Drei Könige", "value" : False, "selected": False},
            {"label" : "Jahrestag der Ausrufung der Republik Neuenburg", "value" : False, "selected": False},
            {"label" : "Josefstag", "value" : False, "selected": False},
            {"label" : "Karfreitag", "value" : True, "selected": True},
            {"label" : "Ostermontag", "value" : True, "selected": True},
            {"label" : "Fahrtsfest", "value" : False, "selected": False},
            {"label" : "Tag der Arbeit", "value" : False, "selected": False},
            {"label" : "Auffahrt", "value" : True, "selected": True},
            {"label" : "Pfingstmontag", "value" : True, "selected": True},
            {"label" : "Frohnleichnam", "value" : False, "selected": False},
            {"label" : "Commémoration du Plébiscite Jurassien", "value" : False, "selected": False},
            {"label" : "Peter und Paul", "value" : False, "selected": False},
            {"label" : "Bundesfeier", "value" : True, "selected": True},
            {"label" : "Mariä Himmelfahrt", "value" : False, "selected": False},
            {"label" : "Jeûne Genevois", "value" : False, "selected": False},
            {"label" : "Lundi du Jeûne", "value" : False, "selected": False},
            {"label" : "Mauritiustag", "value" : False, "selected": False},
            {"label" : "Bruderklausenfest", "value" : False, "selected": False},
            {"label" : "Allerheiligen", "value" : False, "selected": False},
            {"label" : "Mariä Empfängnis", "value" : False, "selected": False},
            {"label" : "Weihnachtstag", "value" : True, "selected": True},
            {"label" : "Stephanstag", "value" : True, "selected": True},
            {"label" : "Restauration de la République", "value" : False, "selected": False},
        ],
    }

    cantons = list(canton_change.keys())

    # --- INPUT --- #

    output.put_buttons(
        ["< Back to piccolaw.ch", "Restart App", "Feedback"],
        small=True,
        onclick=btn_click)
        
    output.put_markdown(lang("""
        # Deadline Calculator
        `v0.0.1 | Updated: XXXX-XX-XX`
        """,
        """
        # Fristenrechner
        `v0.0.1 | Updated: XXXX-XX-XX`
        """))

    with output.use_scope("scope_input_instructions", clear=True):
        output.put_markdown(lang("""
            ### Input

            Please enter your information.

            Notes:
            - Format for all date inputs: DD.MM.YYYY (e.g. 01.01.2020, 16.05.2020, 07.12.2020)
            - End date is optional, leave empty to only evaluate the end of the deadline

            ""","""
            ### Input

            Please enter your information.

            Notes:
            - Format for all date inputs: DD.MM.YYYY (e.g. 01.01.2020, 16.05.2020, 07.12.2020)
            - End date is optional, leave empty to only evaluate the end of the deadline
            """))

    # User input
    deadline_input = input.input_group("", [
        input.select(
            lang(
                "Type of receipt",
                "Empfangsart"),
            options = labels,
            name="receipt_type",
            required=True,
            onchange=lambda c: input.input_update("receipt_std", label = label_change[c])),
        input.input(
            label = label_change[labels[0]],
            name="receipt_std",
            type=input.TEXT,
            required=True,
            pattern="[0-9]{2}\.[0-9]{2}\.(19|20)\d{2}$",
            maxlength="10",
            minlength="10"),
        input.select(
            lang(
                "Court Holidays",
                "Gerichtsferien"),
            options=[{
                    "label":lang("Disable", "Deaktivieren"),
                    "value":False
                    },{
                    "label":lang("Enable", "Aktivieren"),
                    "value":True
                    }],
            name="court_holidays",
            required=True),
        input.select(
            label = "Kanton",
            options = cantons,
            name = "canton",
            required = True,
            onchange=lambda c: input.input_update("holiday_cb", options = canton_change[c])),
        input.checkbox(
            label = "Feiertage",
            options = canton_change[cantons[0]],
            name = "holiday_cb",
            multiple = True)
        ])

